build_api:
    go build -o bin/api_dev cmd/api/main.go

build_cli:
    go build -o bin/cli_dev cmd/cli/main.go

run_api:
    air

run_cli:
    go run sandbox/cmd/cli

install_deps:
    go install github.com/cosmtrek/air@v1.49.0
